# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c9cb77ae-2e9d-4744-861b-9520e55cf07c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c9cb77ae-2e9d-4744-861b-9520e55cf07c".device = "/dev/disk/by-uuid/c9cb77ae-2e9d-4744-861b-9520e55cf07c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/84EC-00E4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-8b1f2dc2-3daf-497c-9e94-737157c54d85"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
