# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-858832cb-b17a-46c6-aefd-5aa0783ae4b8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-858832cb-b17a-46c6-aefd-5aa0783ae4b8".device = "/dev/disk/by-uuid/858832cb-b17a-46c6-aefd-5aa0783ae4b8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B8D8-6D56";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b2a5dc40-ccd0-420f-b2a6-fac62e8186fe"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
